### ISSUE TITLE
Check for location.hash

### ISSUE THREAD

**Issue by zonzujiro** [kottans-frontend-2018/pizza-app-OleksiyRudenko#10]
https://github.com/kottans-frontend-2018/pizza-app-OleksiyRudenko/blob/b017beed02b5a211851a88eecdc3caf6f05979c3/src/components/Router/Router.js#L21

I'm not sure, but I think you should do this after adding listener to `hashchange`.

Also, can I suggest you use `navigateTo` for consistency? Instead of direct changing `window.location.hash`.

**Comment by zonzujiro** [comment]
> I'm not sure, but I think you should do this after adding listener to hashchange.

May bad. It is not necessary.

**Comment by OleksiyRudenko** [comment]
Thanks! Fast-and-dirty solutions has to be refactored as code gets improved.
Fixed.
