### ISSUE TITLE
Redundant Object.assign

### ISSUE THREAD

**Issue by zonzujiro** [kottans-frontend-2018/pizza-app-OleksiyRudenko#8]
https://github.com/kottans-frontend-2018/pizza-app-OleksiyRudenko/blob/b017beed02b5a211851a88eecdc3caf6f05979c3/src/components/Router/Router.js#L82

I think you can just use `{}` here :)

**Comment by OleksiyRudenko** [comment]
Fixed by 57b92ce2621caeb6e9655bda5db73cc82783ce64
