### ISSUE TITLE
Using of DocumentFragment or <template> with string as innerHtml will make this code a lot more easer

### ISSUE THREAD

**Issue by zonzujiro** [kottans-frontend-2018/pizza-app-OleksiyRudenko#9]
https://github.com/kottans-frontend-2018/pizza-app-OleksiyRudenko/blob/b017beed02b5a211851a88eecdc3caf6f05979c3/src/utils/dom.js#L13

**Comment by OleksiyRudenko** [comment]
Fixed by 956b2b314257c67a0b8a985b9c9eb6f0e70015a1
